spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tutorial
    username: tutorial
    password: tutorial
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
